version: "3.8"

services:
  #Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  #Backend API
  face-recognition-api:
    container_name: backend
    #image: node:14.15.4
    build: ./
    command: npm start
    env_file: .env
    working_dir: /usr/faceRecognitionApi
    environment:
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/faceRecognitionApi
