version: "3.8"

services:
  #Postgress
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-recognition-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  #Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  #Backend API
  face-recognition-api:
    container_name: backend
    #image: node:14.15.4
    build: ./
    command: npm start
    working_dir: /usr/faceRecognitionApi
    environment:
      POSTGRES_URI: postgres://admin:secret@postgres:5432/face-recognition-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/faceRecognitionApi
